//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla helgdagar.
        /// </summary>
        internal static string Home_All_Official_Holidays {
            get {
                return ResourceManager.GetString("Home_All_Official_Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla Söndagar.
        /// </summary>
        internal static string Home_All_Sunday_Days {
            get {
                return ResourceManager.GetString("Home_All_Sunday_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontorstid.
        /// </summary>
        internal static string Home_Business_Hours {
            get {
                return ResourceManager.GetString("Home_Business_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxin är ett familjeföretag baserat i Växjö med avsikt att skapa jobbmöjligheter. Vårt mål är att anställa och hjälpa människor med diverse bakgrund och kunskap. Med erfaren personal tillhandahåller vi städtjänster för hushåll, företag, byggarbetsplatser, och generell flytt och storstädning. Även för kundernas tillhandahåller vi interior målnings tjänster. Vi arbetar i följande kommuner: Växjö, Alvesta, Uppvidinge, Tingsryd, Lessebo, Ljungby och Älmhult.Som städföretag är kundtjänst och kundnöjdhet vårt uppd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Home_DescrOxinhem {
            get {
                return ResourceManager.GetString("Home_DescrOxinhem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inom familjen Oxin är personal det viktigaste i vår verksamhet som familj..
        /// </summary>
        internal static string Home_DescrTeam {
            get {
                return ResourceManager.GetString("Home_DescrTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eller maila oss:.
        /// </summary>
        internal static string Home_Email {
            get {
                return ResourceManager.GetString("Home_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FÖR NÖDFALL.
        /// </summary>
        internal static string Home_For_Emergency_Cases {
            get {
                return ResourceManager.GetString("Home_For_Emergency_Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måndag - Fredag.
        /// </summary>
        internal static string Home_Monday_Friday {
            get {
                return ResourceManager.GetString("Home_Monday_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öppningsdagar:.
        /// </summary>
        internal static string Home_Opening_Days {
            get {
                return ResourceManager.GetString("Home_Opening_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vårt lag.
        /// </summary>
        internal static string Home_OurTeam {
            get {
                return ResourceManager.GetString("Home_OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer:.
        /// </summary>
        internal static string Home_Phone {
            get {
                return ResourceManager.GetString("Home_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        internal static string Home_Request_Address {
            get {
                return ResourceManager.GetString("Home_Request_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din adress.
        /// </summary>
        internal static string Home_Request_Address_Hint {
            get {
                return ResourceManager.GetString("Home_Request_Address_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMRÅDE.
        /// </summary>
        internal static string Home_Request_Area {
            get {
                return ResourceManager.GetString("Home_Request_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALKONG.
        /// </summary>
        internal static string Home_Request_Balcony {
            get {
                return ResourceManager.GetString("Home_Request_Balcony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        internal static string Home_Request_Email {
            get {
                return ResourceManager.GetString("Home_Request_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postadress.
        /// </summary>
        internal static string Home_Request_Email_Hint {
            get {
                return ResourceManager.GetString("Home_Request_Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARAGE.
        /// </summary>
        internal static string Home_Request_Garage {
            get {
                return ResourceManager.GetString("Home_Request_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOKA TID.
        /// </summary>
        internal static string Home_Request_Make_an_Appointment {
            get {
                return ResourceManager.GetString("Home_Request_Make_an_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDDELANDE.
        /// </summary>
        internal static string Home_Request_Message {
            get {
                return ResourceManager.GetString("Home_Request_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt meddelande.
        /// </summary>
        internal static string Home_Request_Message_Hint {
            get {
                return ResourceManager.GetString("Home_Request_Message_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        internal static string Home_Request_Name {
            get {
                return ResourceManager.GetString("Home_Request_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt namn.
        /// </summary>
        internal static string Home_Request_Name_Hint {
            get {
                return ResourceManager.GetString("Home_Request_Name_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string Home_Request_Phone_number {
            get {
                return ResourceManager.GetString("Home_Request_Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÄLJ TJÄNSTER.
        /// </summary>
        internal static string Home_Request_Service_Select {
            get {
                return ResourceManager.GetString("Home_Request_Service_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVADRATMETER.
        /// </summary>
        internal static string Home_Request_SquareMeters {
            get {
                return ResourceManager.GetString("Home_Request_SquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAGRING.
        /// </summary>
        internal static string Home_Request_Storage {
            get {
                return ResourceManager.GetString("Home_Request_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lördag.
        /// </summary>
        internal static string Home_Saturday {
            get {
                return ResourceManager.GetString("Home_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAG &amp; PERSONAL.
        /// </summary>
        internal static string Home_TeamStaff {
            get {
                return ResourceManager.GetString("Home_TeamStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ha dina platser rena?.
        /// </summary>
        internal static string Home_TextPic1 {
            get {
                return ResourceManager.GetString("Home_TextPic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du förnya interiörfärger?.
        /// </summary>
        internal static string Home_TextPic2 {
            get {
                return ResourceManager.GetString("Home_TextPic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Så tveka inte att boka tid!.
        /// </summary>
        internal static string Home_TextPic3 {
            get {
                return ResourceManager.GetString("Home_TextPic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        internal static string Home_Vacations {
            get {
                return ResourceManager.GetString("Home_Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÄLKOMMEN TILL OXINHEM.SE.
        /// </summary>
        internal static string Home_Welcome_to_Oxinhem {
            get {
                return ResourceManager.GetString("Home_Welcome_to_Oxinhem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEM VI ÄR ....
        /// </summary>
        internal static string Home_WHO_WE_ARE {
            get {
                return ResourceManager.GetString("Home_WHO_WE_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om oss.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Städning.
        /// </summary>
        internal static string Menu_Cleaning {
            get {
                return ResourceManager.GetString("Menu_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hem.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Målning.
        /// </summary>
        internal static string Menu_Painting {
            get {
                return ResourceManager.GetString("Menu_Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prislista.
        /// </summary>
        internal static string Menu_Pricing {
            get {
                return ResourceManager.GetString("Menu_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka meddelande.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du frågor?.
        /// </summary>
        internal static string Shared_Have_Questions {
            get {
                return ResourceManager.GetString("Shared_Have_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxin Company.
        /// </summary>
        internal static string Shared_OxinCompany {
            get {
                return ResourceManager.GetString("Shared_OxinCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to För att se våra senaste erbjudanden, följ oss på instagram och facebook.
        /// </summary>
        internal static string Shared_OxinhemAbout {
            get {
                return ResourceManager.GetString("Shared_OxinhemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snabblänkar.
        /// </summary>
        internal static string Shared_Quick_Links {
            get {
                return ResourceManager.GetString("Shared_Quick_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ämne.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemsida.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
